// GENERATED by generate-config.js — do not edit by hand.
// Change frontend/.env (local) or the Vercel environment variables (deployed),
// then re-run: node generate-config.js
window.APP_CONFIG = {
    // Empty means "same origin", which is what the local root app.py serves.
    API_BASE_URL: "",
    WAKE_BACKEND: true,
    MAX_UPLOAD_MB: 10,
};

window.API_BASE_URL = window.APP_CONFIG.API_BASE_URL;
