#!/usr/bin/env node
/**
 * Writes config.js from environment variables.
 *
 * A static page cannot read a .env file, so the values are baked into a small
 * script the page loads before script.js. Two callers:
 *
 *   - Vercel, as the build command (values from the project's env settings)
 *   - you, locally: `node generate-config.js`
 *
 * Real environment variables take priority; the local .env file is the
 * fallback. Uses no dependencies so it runs on a bare Vercel build image.
 */

const fs = require("fs");
const path = require("path");

const DEFAULTS = {
    API_BASE_URL: "",
    WAKE_BACKEND: "true",
    MAX_UPLOAD_MB: "10",
};

function readDotEnv(file) {
    if (!fs.existsSync(file)) return {};
    const out = {};
    for (const raw of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
        const line = raw.trim();
        if (!line || line.startsWith("#")) continue;
        const eq = line.indexOf("=");
        if (eq === -1) continue;
        const key = line.slice(0, eq).trim();
        let value = line.slice(eq + 1).trim();
        // strip one layer of matching quotes
        if (value.length > 1 && /^(".*"|'.*')$/.test(value)) value = value.slice(1, -1);
        out[key] = value;
    }
    return out;
}

const fileEnv = readDotEnv(path.join(__dirname, ".env"));
const resolve = (key) => {
    const fromProcess = process.env[key];
    if (fromProcess !== undefined && fromProcess !== "") return fromProcess;
    if (fileEnv[key] !== undefined && fileEnv[key] !== "") return fileEnv[key];
    return DEFAULTS[key];
};

const apiBaseUrl = resolve("API_BASE_URL").replace(/\/+$/, "");
const wakeBackend = String(resolve("WAKE_BACKEND")).toLowerCase() === "true";
const maxUploadMb = Number(resolve("MAX_UPLOAD_MB")) || Number(DEFAULTS.MAX_UPLOAD_MB);

if (apiBaseUrl && !/^https?:\/\//.test(apiBaseUrl)) {
    console.error(`generate-config: API_BASE_URL must start with http:// or https:// (got "${apiBaseUrl}")`);
    process.exit(1);
}

const contents = `// GENERATED by generate-config.js — do not edit by hand.
// Change frontend/.env (local) or the Vercel environment variables (deployed),
// then re-run: node generate-config.js
window.APP_CONFIG = {
    // Empty means "same origin", which is what the local root app.py serves.
    API_BASE_URL: ${JSON.stringify(apiBaseUrl)},
    WAKE_BACKEND: ${wakeBackend},
    MAX_UPLOAD_MB: ${maxUploadMb},
};

window.API_BASE_URL = window.APP_CONFIG.API_BASE_URL;
`;

fs.writeFileSync(path.join(__dirname, "config.js"), contents);
console.log(`generate-config: wrote config.js (API_BASE_URL=${apiBaseUrl || "<same origin>"}, ` +
            `wakeBackend=${wakeBackend}, maxUploadMb=${maxUploadMb})`);
